/* BLACKOUT v9: OPERATOR UPDATE. Drop-in skills, abilities, upgrades and start UX. */
'use strict';
(function(BO){
const U=BO.U,S=BO.SaveSystem,I=BO.I18N,C=BO.Collision,G=BO.Game.prototype,P=BO.Player.prototype,UI=BO.UIManager.prototype;
if(!U||!S||!G||!P||!UI)return;
const B={assault:'#ff8a1a',shadow:'#b07cff',tech:'#19c3dd'}, BR=['assault','shadow','tech'];
const D={brute:{b:'assault',t:1,m:3,p:1},overcharge:{b:'assault',t:2,m:3,p:1,a:1,cd:30,d:[5,6.5,8]},executioner:{b:'assault',t:3,m:3,p:1},blast:{b:'assault',t:4,m:3,p:1,a:1,cd:22,d:[55,80,105]},silent:{b:'shadow',t:1,m:3,p:1},sonar:{b:'shadow',t:2,m:3,p:1,a:1,cd:20,d:[4,5.5,7]},cloak:{b:'shadow',t:3,m:3,p:1,a:1,cd:34,d:[4,5,6]},medic:{b:'tech',t:1,m:3,p:1},drone:{b:'tech',t:2,m:3,p:1,a:1,cd:32,d:[10,13,16]},overclock:{b:'tech',t:3,m:3,p:1},barrier:{b:'tech',t:4,m:3,p:1,a:1,cd:26,d:[3.5,4.5,5.5]}};
const IDS=Object.keys(D), TL=[0,1,3,5,8], NEW=[['stamina',240,'mobility'],['dodge',320,'mobility'],['regen',380,'survival'],['lifesteal',340,'survival'],['crit',420,'weapons'],['scavenger',300,'support'],['cooldown',400,'support']], CAT={maxHp:'survival',armor:'survival',speed:'mobility',reload:'weapons',damage:'weapons',accuracy:'weapons',magazine:'weapons'};
NEW.forEach(x=>{CAT[x[0]]=x[2];if(!BO.UpgradeSystem.list.some(y=>y.id===x[0]))BO.UpgradeSystem.list.push({id:x[0],base:x[1],icon:x[0]});if(BO.UPGRADE_IDS&&BO.UPGRADE_IDS.indexOf(x[0])<0)BO.UPGRADE_IDS.push(x[0])});
const rank=(id,s)=>s.v9.r[id]||0, data=s=>s.v9||(s.v9={r:{},e:[null,null]}), up=id=>(S.data.upgrades&&S.data.upgrades[id])||0;
const clean=v=>{const o={r:{},e:[null,null]};if(!v||typeof v!=='object')return o;IDS.forEach(id=>{if(+v.r?.[id]>0)o.r[id]=U.clamp(Math.floor(+v.r[id]),0,D[id].m)});(v.e||[]).slice(0,2).forEach((id,i)=>{if(D[id]?.a&&rank(id,{v9:o})>0)o.e[i]=id});return o};
const raw=()=>{try{return JSON.parse((S.storage?S.storage.get(S.key):localStorage.getItem(S.key))||'null')}catch(e){return null}};
const oldLoad=S.load;S.load=function(){const d=oldLoad.apply(this,arguments),r=raw();d.v9=clean(r?.v9);NEW.forEach(x=>d.upgrades[x[0]]=U.isFiniteNumber(r?.upgrades?.[x[0]])?U.clamp(Math.floor(r.upgrades[x[0]]),0,5):0);return d};
const Skill={rank:(id,s=S.data)=>rank(id,s),spent:s=>IDS.reduce((n,id)=>n+rank(id,s),0),points:s=>Math.max(0,(s.level||1)-Skill.spent(s)),prev:id=>IDS.find(x=>D[x].b===D[id].b&&D[x].t===D[id].t-1),can:(id,s=S.data)=>D[id]&&rank(id,s)<D[id].m&&Skill.points(s)>0&&(s.level||1)>=TL[D[id].t]&&(!Skill.prev(id)||rank(Skill.prev(id),s)>0),learn(id,s=S.data){if(!this.can(id,s))return false;data(s).r[id]=rank(id,s)+1;const z=data(s);if(D[id].a&&!z.e.includes(id))z.e[z.e.indexOf(null)<0?0:z.e.indexOf(null)]=id;return true},equip(id,slot,s=S.data){const z=data(s),j=z.e.indexOf(id);if(!D[id]?.a||!rank(id,s))return false;if(j===slot){z.e[slot]=null;return true}if(j>=0)z.e[j]=z.e[slot];z.e[slot]=id;return true},respec(s=S.data){s.v9={r:{},e:[null,null]}}};BO.Skills=Skill;
function st(p){return p.v9x||(p.v9x={cd:[0,0],t:{},last:0,streak:0,drone:null,ghost:null})}function ps(g){return g.coop&&g.players?g.players:[g.player]}function on(p,k){return st(p).t[k]>0}function announce(g,p,id){g.ui.notify(BO.t('sk.'+id),B[D[id].b],1.4)}
const odmg=P.damageMul,orate=P.rateMul,ofire=P._fire,omove=P._updateMovement,ododge=P._startDodge,otake=P.takeDamage;
P.damageMul=function(){let x=odmg.apply(this,arguments);if(Skill.rank('brute'))x*=1+.05*Skill.rank('brute');if(on(this,'overcharge'))x*=1.2;if(on(this,'cloak'))x*=2;return x};P.rateMul=function(){let x=orate.apply(this,arguments);return on(this,'overcharge')?x*1.35:x};P._fire=function(g,w){const m=w?.mag,r=ofire.apply(this,arguments);if(on(this,'overcharge')&&w&&m>w.mag)w.mag=m;if(on(this,'cloak'))st(this).t.cloak=0;return r};P._updateMovement=function(dt,i,g){const l=up('stamina'),a=BO.CONFIG.STAMINA_DRAIN,b=BO.CONFIG.STAMINA_REGEN;if(l){BO.CONFIG.STAMINA_DRAIN=a*(1-.1*l);BO.CONFIG.STAMINA_REGEN=b*(1+.12*l)}try{return omove.apply(this,arguments)}finally{BO.CONFIG.STAMINA_DRAIN=a;BO.CONFIG.STAMINA_REGEN=b}};P._startDodge=function(){const r=ododge.apply(this,arguments),l=up('dodge');if(l){this.dodgeCooldown*=1-.08*l;this.iframes+=.03*l}return r};P.takeDamage=function(){const r=otake.apply(this,arguments);if(r>0)st(this).last=arguments[3]?.time||0;return r};
const start=G.startMission;G.startMission=function(id){const ok=start.apply(this,arguments);if(ok){this.v9fx=[];ps(this).forEach(p=>{p.v9x=null;st(p);if(Skill.rank('medic')){p.maxHp+=10*Skill.rank('medic');p.hp=p.maxHp}});if(data(S.data).e.some(Boolean))this.ui.schedule(2,()=>this.ui.notify(BO.t('sk.ready'),B.shadow,4))}return ok};
const dmg=G.damageEnemy;G.damageEnemy=function(e,n,x,y,info){if(info?.source==='player'&&!e.dead){if(Skill.rank('executioner')&&e.hp/e.maxHp<.35)n*=1+.12*Skill.rank('executioner');if(Skill.rank('ambush')&&!e.engaged)n*=1+.2*Skill.rank('ambush')}return dmg.call(this,e,n,x,y,info)};
const kill=G.onEnemyKilled;G.onEnemyKilled=function(e,info){const r=kill.apply(this,arguments),p=this.player,s=st(p);if(info?.source!=='hazard'&&info?.source!=='enemy'){const h=3*(up('lifesteal')+Skill.rank('medic'));if(h)p.heal(h);s.cd=s.cd.map(x=>Math.max(0,x-.5));s.streak=this.time-s.last<3.5?s.streak+1:1;s.last=this.time;if(s.streak>1){this.grantXP(10*(s.streak-1));this.ui.notify(BO.t('streak.'+Math.min(5,s.streak)),B.assault,1.2)}}return r};
const cred=G.addCredits;G.addCredits=function(n){return cred.call(this,up('scavenger')?Math.round(n*(1+.08*up('scavenger'))):n)};
const vis=G._updateVisibility;G._updateVisibility=function(){const r=vis.apply(this,arguments);this.enemies?.forEach(e=>{if(!e.dead&&e.v9reveal>0)e.visible=true});return r};
const ai=BO.AISystem?.prototype;if(ai){const au=ai.update,ue=ai._updateEnemy,noise=ai.onNoise;ai._updateEnemy=function(e,dt){if(e.v9stun>0){e.v9stun-=dt;e.vx=e.vy=0;return}return ue.apply(this,arguments)};ai.onNoise=function(x,y,r,f){const l=Skill.rank('silent');return noise.call(this,x,y,r*(l&&f?1-.12*l:1),f)};ai.update=function(dt){const g=this.game;if(ps(g).some(p=>on(p,'cloak'))){const q=g.player;try{const p=ps(g).find(x=>on(x,'cloak'));g.player={x:p.x,y:p.y,dead:false};return au.call(this,dt)}finally{g.player=q}}return au.apply(this,arguments)}}
function cast(g,p,id,r){const s=st(p),d=D[id];if(id==='overcharge'){s.t.overcharge=d.d[r];g.addLight(p.x,p.y,260,B.assault,.5,.8);return}if(id==='barrier'){s.t.barrier=d.d[r];return}if(id==='cloak'){s.t.cloak=d.d[r];s.ghost={x:p.x,y:p.y};return}if(id==='sonar'){g.enemies.forEach(e=>{if(!e.dead&&U.dist(p.x,p.y,e.x,e.y)<1100)e.v9reveal=Math.max(e.v9reveal||0,d.d[r])});g.ui.notify(BO.t('sk.sonarHits'),B.shadow,2);return}if(id==='blast'){g.explode(p.x,p.y,210,d.d[r],'player',{small:true});g.enemies.forEach(e=>{if(!e.dead&&U.dist(p.x,p.y,e.x,e.y)<230&&!e.isBoss)e.v9stun=1.2+r*.4;});return}if(id==='drone'){s.t.drone=d.d[r];s.drone={t:d.d[r],fire:0}}}
function ability(g,p,slot){const id=data(S.data).e[slot],s=st(p);if(!id)return g.ui.notify(BO.t('sk.noAbility'),'#9aa0b4',1.5);if(s.cd[slot]>0)return g.ui.notify(BO.t('sk.cooldown',{n:I.num(Math.ceil(s.cd[slot]))}), '#ff8095',1.2);const d=D[id],r=Skill.rank(id)-1;cast(g,p,id,r);s.cd[slot]=d.cd*(1-.08*Skill.rank('overclock')-.05*up('cooldown'));announce(g,p,id)}
const upd=G._update;G._update=function(dt){upd.apply(this,arguments);if(!this.player)return;ps(this).forEach(p=>{const s=st(p),i=p.isP2?p.v6in:this.input;if(!i)return;Object.keys(s.t).forEach(k=>s.t[k]=Math.max(0,s.t[k]-dt));s.cd=s.cd.map(x=>Math.max(0,x-dt));if(i.wasPressed('KeyC')||i.wasPressed('V9A1'))ability(this,p,0);if(i.wasPressed('KeyV')||i.wasPressed('V9A2'))ability(this,p,1);if(s.t.drone){s.drone.t-=dt;if(s.drone.t<=0)s.t.drone=0;else{const e=this.enemies.find(e=>!e.dead&&!e.isBoss);if(e&&s.drone.fire<=0){s.drone.fire=.35;this.damageEnemy(e,9+3*Skill.rank('drone'),0,0,{x:e.x,y:e.y,source:'player'})}s.drone.fire-=dt}}});this.enemies?.forEach(e=>{if(e.v9reveal>0)e.v9reveal-=dt});};
if(BO.ProjectileSystem){const sp=BO.ProjectileSystem.prototype.spawn,os=BO.ProjectileSystem.prototype;os.spawn=function(x){if(x?.owner===0)x.critChance=(x.critChance||0)+.025*up('crit');return sp.apply(this,arguments)}}
/* UI */
if(typeof document==='undefined')return;const $=(q,r)=> (r||document).querySelector(q), F=h=>{const t=document.createElement('template');t.innerHTML=h.trim();return t.content.firstChild};
const css=document.createElement('style');css.textContent='.v9torch{position:absolute;inset:0;pointer-events:none;background:radial-gradient(420px circle at var(--mx,70%) var(--my,40%),rgba(255,170,90,.12),transparent 70%)}.v9d{position:absolute;top:50%;inset-inline-end:4vw;transform:translateY(-50%);width:min(360px,32vw);padding:20px;background:rgba(10,12,22,.86);border-top:3px solid var(--blaze);z-index:2}.v9d h3{margin:0 0 14px;color:var(--muted);letter-spacing:.16em;font-size:12px}.v9d .v9ring{font:700 56px var(--display);color:var(--tech);border:6px solid rgba(25,195,221,.3);border-radius:50%;width:100px;height:100px;display:flex;align-items:center;justify-content:center;float:left;margin-right:14px}.v9d b{font-size:20px}.v9d .v9stats{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:18px;clear:both}.v9d .v9stats div{padding:8px;background:rgba(255,255,255,.04);color:var(--muted);font-size:11px}.v9d .v9stats b{display:block;color:var(--text);font-size:19px}.v9d .v9next{margin-top:12px;padding:12px;border:1px solid rgba(255,138,26,.35);color:var(--blaze)}.v9d .v9next b{display:block;font:700 25px var(--display);color:var(--text)}.v9d .v9tip{margin:12px 0 0;color:var(--muted);font-size:13px;line-height:1.5}.v9skills{width:min(1120px,96vw)}.v9hint{padding:0 32px;color:var(--muted)}.v9tree{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:0 32px 18px;overflow:auto}.v9branch h3{color:var(--c);font:700 28px var(--display);margin:0;padding:10px;border-top:3px solid var(--c)}.v9node{padding:12px;margin:8px 0;border:1px solid var(--line);background:rgba(255,255,255,.025);border-inline-start:3px solid var(--c)}.v9node.lock{opacity:.45}.v9node b{font-size:16px}.v9node p{color:var(--muted);font-size:13px;line-height:1.45;margin:5px 0 10px}.v9node button{padding:7px 10px;border:1px solid var(--c);color:var(--c);font-weight:700}.v9node button:disabled{opacity:.45}.v9eq{display:flex;gap:8px;padding:0 32px 14px;flex-wrap:wrap}.v9eq span{padding:8px 14px;background:rgba(255,255,255,.04);border-inline-start:3px solid var(--c)}@media(max-width:1100px){.v9d{display:none}.v9tree{grid-template-columns:1fr}}';document.head.appendChild(css);
const m=$('[data-screen="menu"]');if(m){m.insertBefore(F('<div class="v9torch"></div>'),m.firstChild);m.insertBefore(F('<button class="nav" data-action="v9skills" data-i18n="menu.skills"></button>'),$('[data-action="settings"]',m));m.appendChild(F('<aside class="v9d"><h3 data-i18n="v9.dossier"></h3><div class="v9ring" id="v9lvl"></div><b id="v9rank"></b><div id="v9xp"></div><div class="v9stats"><div>OPS <b id="v9ops"></b></div><div>KILLS <b id="v9kills"></b></div><div>CREDITS <b id="v9credits"></b></div><div>S RATINGS <b id="v9s"></b></div></div><div class="v9next"><small data-i18n="v9.nextOp"></small><b id="v9op"></b></div><p class="v9tip" id="v9tip"></p></aside>'));m.addEventListener('mousemove',e=>{m.style.setProperty('--mx',e.clientX+'px');m.style.setProperty('--my',e.clientY+'px')})}
const scr=F('<section class="screen panel-screen" data-screen="v9skills"><div class="panel wide v9skills"><header class="panel-head"><h2 data-i18n="sk.title"></h2><span class="head-credits"><span data-i18n="sk.points"></span> <b id="v9pts"></b></span></header><p class="v9hint" data-i18n="sk.hint"></p><div class="v9eq" id="v9eq"></div><div class="v9tree" id="v9tree"></div><footer class="panel-foot"><button class="btn" data-action="back" data-i18n="common.back"></button><button class="btn danger" data-action="v9respec" data-i18n="sk.respec"></button></footer></div></section>');$('[data-screen="upgrades"]')?.parentNode.insertBefore(scr,$('[data-screen="upgrades"]').nextSibling);
function menu(ui){const s=ui.game.save.data,n=BO.UpgradeSystem.xpForLevel(s.level);$('#v9lvl').textContent=I.num(s.level);$('#v9rank').textContent=BO.t('rank.'+(s.level>=20?5:s.level>=15?4:s.level>=10?3:s.level>=6?2:s.level>=3?1:0));$('#v9xp').textContent=BO.t('v9.xpTo',{a:I.num(s.xp),b:I.num(n)});$('#v9ops').textContent=I.num(s.completedMissions.length);$('#v9kills').textContent=I.num(s.stats?.kills||0);$('#v9credits').textContent=I.num(s.credits);$('#v9s').textContent=I.num(Object.values(s.bestRatings||{}).filter(x=>x==='S').length);const nx=BO.MissionSystem.nextMission(s);$('#v9op').textContent=nx?BO.t(nx.nameKey):BO.t('v9.allDone');$('#v9tip').textContent=BO.t('v9.tip'+(1+(Date.now()/8000|0)%5))}
const oldProf=UI.renderProfile;UI.renderProfile=function(){oldProf.apply(this,arguments);menu(this)};
function skills(ui){const s=ui.game.save.data,z=data(s);$('#v9pts').textContent=I.num(Skill.points(s));$('#v9eq').innerHTML=z.e.map((id,i)=>`<span style="--c:${id?B[D[id].b]:'#5c6072'}">${i?'V':'C'} · ${id?BO.t('sk.'+id):BO.t('sk.empty')}</span>`).join('');const tree=$('#v9tree');tree.innerHTML='';BR.forEach(b=>{const c=document.createElement('div');c.className='v9branch';c.style.setProperty('--c',B[b]);c.innerHTML=`<h3>${BO.t('skb.'+b)}</h3>`;IDS.filter(id=>D[id].b===b).sort((a,x)=>D[a].t-D[x].t).forEach(id=>{const d=D[id],r=rank(id,s),ok=Skill.can(id,s),lock=(s.level||1)<TL[d.t]||!!Skill.prev(id)&&!rank(Skill.prev(id),s);const n=F(`<div class="v9node ${lock?'lock':''}"><b>${BO.t('sk.'+id)}</b><p>${BO.t('sk.'+id+'.d')}</p><button data-action="v9learn" data-id="${id}">${r>=d.m?BO.t('sk.maxed'):lock?BO.t('sk.locked',{n:TL[d.t]}):ok?(r?BO.t('sk.rankUp'):BO.t('sk.learn')):BO.t('sk.noPoints')}</button>${d.a&&r?` <button data-action="v9equip" data-id="${id}" data-slot="0">[C]</button><button data-action="v9equip" data-id="${id}" data-slot="1">[V]</button>`:''}</div>`);n.querySelectorAll('button').forEach(x=>x.disabled=x.dataset.action==='v9learn'&&!ok);c.appendChild(n)});tree.appendChild(c)})}
const showSkills=ui=>{ui.show('v9skills');skills(ui)};const root=document.getElementById('ui');root?.addEventListener('click',e=>{const x=e.target.closest('[data-action]');if(!x||!BO.game)return;const u=BO.game.ui;if(x.dataset.action==='v9skills')showSkills(u);if(x.dataset.action==='v9learn'){if(Skill.learn(x.dataset.id))S.save();skills(u)}if(x.dataset.action==='v9equip'){Skill.equip(x.dataset.id,+x.dataset.slot);S.save();skills(u)}if(x.dataset.action==='v9respec')u._confirm(BO.t('sk.respecConfirm'),()=>{Skill.respec();S.save();skills(u)})});

BO.I18N.extend('en',{'menu.skills':'SKILLS','v9.dossier':'OPERATOR DOSSIER','v9.nextOp':'NEXT OPERATION','v9.xpTo':'{a} / {b} XP','v9.allDone':'ALL OPERATIONS CLEARED','v9.tip1':'Press C and V for abilities. Every kill cuts cooldowns.','v9.tip2':'Cloak leaves an afterimage and doubles your first shot.','v9.tip3':'Chain kills within 3.5 seconds for bonus XP.','v9.tip4':'Sonar reveals hostiles through walls.','v9.tip5':'Barrier converts enemy rounds into armor.','sk.title':'SKILLS','sk.points':'POINTS','sk.hint':'One point per player level. Unlock tiers at levels 1, 3, 5 and 8. Equip two abilities to C and V. Respec is free.','sk.respec':'RESPEC (FREE)','sk.respecConfirm':'Refund every skill point? Equipped abilities will be cleared.','sk.empty':'EMPTY SLOT','sk.learn':'LEARN · 1 PT','sk.rankUp':'RANK UP · 1 PT','sk.maxed':'MAXED','sk.locked':'UNLOCKS AT LVL {n}','sk.noPoints':'NO POINTS','sk.ready':'ABILITIES ONLINE','sk.noAbility':'NO ABILITY EQUIPPED','sk.cooldown':'ABILITY READY IN {n}s','sk.sonarHits':'SONAR // HOSTILES TAGGED','skb.assault':'ASSAULT','skb.shadow':'SHADOW','skb.tech':'TECH','sk.brute':'BRUTE FORCE','sk.brute.d':'+5% weapon damage per rank.','sk.overcharge':'OVERCHARGE','sk.overcharge.d':'+35% fire rate and +20% damage for 5 / 6.5 / 8 seconds.','sk.executioner':'EXECUTIONER','sk.executioner.d':'+12% damage to enemies below 35% health per rank.','sk.blast':'CONCUSSION BLAST','sk.blast.d':'Shockwave deals damage, knockback and stun.','sk.silent':'SOFT STEPS','sk.silent.d':'Make 12% less noise per rank.','sk.sonar':'SONAR PULSE','sk.sonar.d':'Reveal nearby hostiles through walls for 4 / 5.5 / 7 seconds.','sk.cloak':'SHADOW CLOAK','sk.cloak.d':'Vanish and leave an afterimage. First shot deals double damage.','sk.medic':'FIELD MEDIC','sk.medic.d':'+10 max health and +3 health per kill per rank.','sk.drone':'SENTRY DRONE','sk.drone.d':'Orbiting drone fires with you for 10 / 13 / 16 seconds.','sk.overclock':'OVERCLOCK','sk.overclock.d':'-8% ability cooldowns per rank.','sk.barrier':'KINETIC BARRIER','sk.barrier.d':'Absorb enemy rounds and convert them to armor.','streak.2':'DOUBLE KILL','streak.3':'TRIPLE KILL','streak.4':'RAMPAGE','streak.5':'UNSTOPPABLE','up.stamina':'ENDURANCE','upd.stamina':'-10% sprint drain and faster stamina regen per level','up.dodge':'REFLEXES','upd.dodge':'-8% dodge cooldown per level','up.regen':'BIO-REGEN','upd.regen':'Regenerate health after 4 seconds without damage','up.lifesteal':'SECOND WIND','upd.lifesteal':'+3 health per kill','up.crit':'PRECISION','upd.crit':'+2.5% critical chance per level','up.scavenger':'SCAVENGER','upd.scavenger':'+8% credits from pickups','up.cooldown':'TACTICAL CORE','upd.cooldown':'-5% ability cooldowns per level','upc.survival':'SURVIVAL','upc.mobility':'MOBILITY','upc.weapons':'WEAPONRY','upc.support':'SUPPORT','up.new':'NEW'});
BO.I18N.extend('fa',{'menu.skills':'مهارت‌ها','v9.dossier':'پرونده مأمور','v9.nextOp':'مأموریت بعدی','v9.xpTo':'{a} / {b} تجربه','v9.allDone':'همه مأموریت‌ها انجام شد','v9.tip1':'با C و V توانایی‌ها را فعال کن. هر حذف زمان شارژ را کم می‌کند.','v9.tip2':'شنل سایه تصویر جا می‌گذارد و اولین شلیک را دو برابر می‌کند.','v9.tip3':'حذف‌های زنجیره‌ای تجربه اضافه می‌دهند.','v9.tip4':'سونار دشمن‌ها را پشت دیوار آشکار می‌کند.','v9.tip5':'سپر گلوله‌های دشمن را به زره تبدیل می‌کند.','sk.title':'مهارت‌ها','sk.points':'امتیاز','sk.hint':'هر سطح یک امتیاز می‌دهد. ردیف‌ها در سطوح ۱، ۳، ۵ و ۸ باز می‌شوند. دو توانایی را روی C و V مجهز کن. بازتنظیم رایگان است.','sk.respec':'بازتنظیم (رایگان)','sk.respecConfirm':'همه امتیازها برگردانده شوند؟','sk.empty':'خالی','sk.learn':'یادگیری · ۱ امتیاز','sk.rankUp':'ارتقا · ۱ امتیاز','sk.maxed':'کامل','sk.locked':'باز در سطح {n}','sk.noPoints':'امتیاز نداری','sk.ready':'توانایی‌ها آماده‌اند','sk.noAbility':'توانایی مجهز نیست','sk.cooldown':'توانایی تا {n} ثانیه دیگر','sk.sonarHits':'سونار // دشمن‌ها علامت خوردند','skb.assault':'یورش','skb.shadow':'سایه','skb.tech':'فناوری','sk.brute':'زور خام','sk.brute.d':'در هر رتبه ۵٪ آسیب سلاح بیشتر.','sk.overcharge':'اضافه‌شارژ','sk.overcharge.d':'سرعت شلیک و آسیب بیشتر برای ۵ / ۶٫۵ / ۸ ثانیه.','sk.executioner':'جلاد','sk.executioner.d':'در هر رتبه ۱۲٪ آسیب بیشتر به دشمن کم‌جان.','sk.blast':'انفجار ضربه‌ای','sk.blast.d':'موج ضربه با آسیب، پرتاب و گیج کردن.','sk.silent':'گام نرم','sk.silent.d':'در هر رتبه ۱۲٪ صدای کمتر.','sk.sonar':'پالس سونار','sk.sonar.d':'دشمن‌های اطراف را پشت دیوار آشکار کن.','sk.cloak':'شنل سایه','sk.cloak.d':'ناپدید شو و تصویر جا بگذار. اولین شلیک دو برابر آسیب می‌زند.','sk.medic':'امدادگر میدانی','sk.medic.d':'در هر رتبه ۱۰ جان بیشتر و ۳ جان برای هر حذف.','sk.drone':'پهپاد نگهبان','sk.drone.d':'پهپاد برای ۱۰ / ۱۳ / ۱۶ ثانیه شلیک می‌کند.','sk.overclock':'اورکلاک','sk.overclock.d':'در هر رتبه ۸٪ شارژ سریع‌تر.','sk.barrier':'سپر جنبشی','sk.barrier.d':'گلوله‌های دشمن را به زره تبدیل کن.','streak.2':'حذف دوتایی','streak.3':'حذف سه‌تایی','streak.4':'کشتار','streak.5':'توقف‌ناپذیر','up.stamina':'استقامت','upd.stamina':'مصرف دویدن کمتر و بازیابی سریع‌تر در هر سطح','up.dodge':'واکنش','upd.dodge':'شارژ سریع‌تر غلت','up.regen':'بازسازی زیستی','upd.regen':'پس از ۴ ثانیه بدون آسیب جان بگیر','up.lifesteal':'نفس دوم','upd.lifesteal':'۳ جان برای هر حذف','up.crit':'دقت مرگبار','upd.crit':'شانس ضربه بحرانی بیشتر','up.scavenger':'لاشخور','upd.scavenger':'اعتبار بیشتر از آیتم‌ها','up.cooldown':'هسته تاکتیکی','upd.cooldown':'شارژ سریع‌تر توانایی‌ها','upc.survival':'بقا','upc.mobility':'تحرک','upc.weapons':'تسلیحات','upc.support':'پشتیبانی','up.new':'جدید'});
})(window.BO);
